version 2.2-2

diff --git a/lib/_MpmOptions b/lib/_MpmOptions
--- a/lib/_MpmOptions
+++ b/lib/_MpmOptions
@@ -14,14 +14,15 @@ _MpmOptions() {
         --edit   |-e)
             editoption=yes
             if [[ -f $playlists_dir/$list ]]; then
-                _EditMyPlaylist
-            else
                 _EditPlaylist
+            else
+                printf '\n%s\n' " ${critical}$list does not exist!${nc}"
+                exit 1
             fi
         ;;
         --help   |-h) less "$HELP" ;;
         --local  |-f) _LoadLocalMenu ;;
-        --version|-v) echo "  ${0##*/} $VERSION" ;;
+        --version|-v) echo -e "\n  ${0##*/} $VERSION" ;;
         --load   |-l)
             if [[ -f $playlists_dir/$list ]]; then
                 _LoadPlaylistMenu
@@ -33,8 +34,7 @@ _MpmOptions() {
             if (( $# == 0 )); then
                 _StartUp
             else
-                __
-                printf '%s\n' " ${critical}invalid option: ${task}$1${nc}"
+                printf '\n%s\n' " ${critical}invalid option: ${task}$1${nc}"
                 head -n 13 "$HELP"; echo $'\e[0m'
                 exit 1
             fi
